# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WanjinToHA
version: "1.2.0"
slug: Wanjin
description: WanjinToHA
url: "https://github.com/timmylau1/WanjinToHA"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  3306/tcp: 3306
  6379/tcp: 6379
  8066/tcp: 8066
  22/tcp: 3888
  
image: "timmylau/artnetforha:v1"
